pub mod admin;
pub mod api_keys;
pub mod dashboard;
pub mod pending;
pub mod register;
pub mod rejected;
pub mod setup;
pub mod signin;
pub mod status;

pub use admin::AdminPage;
pub use api_keys::ApiKeysPage;
pub use dashboard::DashboardPage;
pub use pending::PendingPage;
pub use register::RegisterPage;
pub use rejected::RejectedPage;
pub use setup::SetupPage;
pub use signin::SignInPage;
pub use status::StatusPage;
