use pastedev_core::{SnippetType, Visibility, BURN_AFTER_READ_WINDOW_SECONDS};
use sqlx::PgPool;
use time::OffsetDateTime;
use uuid::Uuid;

#[derive(Debug, Clone)]
pub struct SnippetRow {
    pub id: Uuid,
    pub slug: String,
    pub owner_id: Uuid,
    pub owner_username: String,
    pub kind: SnippetType,
    pub name: Option<String>,
    pub body: String,
    pub size_bytes: i32,
    pub views: i32,
    pub visibility: Visibility,
    /// Absolute timestamp at which non-owner reads stop resolving. `None`
    /// = never expires. Set at creation as `now() + lifetime`; refreshed by
    /// the same formula on `/settings` updates; tightened down to
    /// `LEAST(expires_at, now() + 15min)` when burn-after-read fires.
    pub expires_at: Option<OffsetDateTime>,
    pub burn_after_read: bool,
    pub first_viewed_at: Option<OffsetDateTime>,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

#[derive(Debug)]
pub struct SnippetDraft<'a> {
    pub owner_id: Uuid,
    pub kind: SnippetType,
    pub name: Option<&'a str>,
    pub body: &'a str,
    pub visibility: Visibility,
    /// Already-resolved absolute expiry. The handler converts the user's
    /// `lifetime_seconds` choice into `now() + lifetime` before calling us.
    pub expires_at: Option<OffsetDateTime>,
    pub burn_after_read: bool,
}

struct SnippetRowRaw {
    id: Uuid,
    slug: String,
    owner_id: Uuid,
    owner_username: String,
    kind: String,
    name: Option<String>,
    body: String,
    size_bytes: i32,
    views: i32,
    visibility: String,
    expires_at: Option<OffsetDateTime>,
    burn_after_read: bool,
    first_viewed_at: Option<OffsetDateTime>,
    created_at: OffsetDateTime,
    updated_at: OffsetDateTime,
}

fn map(r: SnippetRowRaw) -> Option<SnippetRow> {
    Some(SnippetRow {
        id: r.id,
        slug: r.slug,
        owner_id: r.owner_id,
        owner_username: r.owner_username,
        kind: r.kind.parse().ok()?,
        name: r.name,
        body: r.body,
        size_bytes: r.size_bytes,
        views: r.views,
        visibility: r.visibility.parse().ok()?,
        expires_at: r.expires_at,
        burn_after_read: r.burn_after_read,
        first_viewed_at: r.first_viewed_at,
        created_at: r.created_at,
        updated_at: r.updated_at,
    })
}

/// Insert a snippet at the given `slug`. The slug is generated by the caller
/// (see [`super::slug::create_with_retry`]) so we can react to collisions.
pub async fn insert<'a>(
    pool: &PgPool,
    slug: &str,
    draft: &SnippetDraft<'a>,
) -> Result<SnippetRow, sqlx::Error> {
    let size = i32::try_from(draft.body.len()).unwrap_or(i32::MAX);
    let inserted_id = sqlx::query!(
        "INSERT INTO snippets (slug, owner_id, type, name, body, size_bytes,
                               visibility, expires_at, burn_after_read)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
         RETURNING id",
        slug,
        draft.owner_id,
        draft.kind.as_str(),
        draft.name,
        draft.body,
        size,
        draft.visibility.as_str(),
        draft.expires_at,
        draft.burn_after_read,
    )
    .fetch_one(pool)
    .await?;
    by_id(pool, inserted_id.id)
        .await?
        .ok_or(sqlx::Error::RowNotFound)
}

/// Atomically handle a non-owner's first read on a `burn_after_read` snippet:
///   1. stamp `first_viewed_at = now()` (no-op if already set)
///   2. tighten `expires_at` down to `LEAST(expires_at, now() + 15min)` so any
///      pre-existing lifetime doesn't outlive the burn window
///
/// Returns the fresh row so the handler can serve a DTO that reflects the new
/// (now imminent) expiry. `Ok(None)` means the snippet either isn't
/// burn-after-read or has been soft-deleted.
pub async fn mark_first_view(
    pool: &PgPool,
    snippet_id: Uuid,
) -> Result<Option<SnippetRow>, sqlx::Error> {
    let burn_window = BURN_AFTER_READ_WINDOW_SECONDS as f64;
    let row = sqlx::query_scalar!(
        "UPDATE snippets
            SET first_viewed_at = COALESCE(first_viewed_at, now()),
                expires_at = LEAST(
                    COALESCE(expires_at, now() + make_interval(secs => $2)),
                    now() + make_interval(secs => $2)
                )
            WHERE id = $1 AND burn_after_read = true AND deleted_at IS NULL
            RETURNING id",
        snippet_id,
        burn_window,
    )
    .fetch_optional(pool)
    .await?;
    match row {
        Some(id) => by_id(pool, id).await,
        None => Ok(None),
    }
}

/// Fetch a snippet by primary key, joined to its owner's username.
pub async fn by_id(pool: &PgPool, id: Uuid) -> Result<Option<SnippetRow>, sqlx::Error> {
    let row = sqlx::query_as!(
        SnippetRowRaw,
        r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                  s.type AS kind, s.name, s.body, s.size_bytes, s.views,
                  s.visibility, s.expires_at, s.burn_after_read,
                  s.first_viewed_at, s.created_at, s.updated_at
           FROM snippets s
           JOIN users u ON u.id = s.owner_id
           WHERE s.id = $1 AND s.deleted_at IS NULL"#,
        id,
    )
    .fetch_optional(pool)
    .await?;
    Ok(row.and_then(map))
}

/// Fetch a snippet by its public slug, joined to its owner's username.
pub async fn by_slug(pool: &PgPool, slug: &str) -> Result<Option<SnippetRow>, sqlx::Error> {
    let row = sqlx::query_as!(
        SnippetRowRaw,
        r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                  s.type AS kind, s.name, s.body, s.size_bytes, s.views,
                  s.visibility, s.expires_at, s.burn_after_read,
                  s.first_viewed_at, s.created_at, s.updated_at
           FROM snippets s
           JOIN users u ON u.id = s.owner_id
           WHERE s.slug = $1 AND s.deleted_at IS NULL"#,
        slug,
    )
    .fetch_optional(pool)
    .await?;
    Ok(row.and_then(map))
}

/// Soft-delete a snippet owned by `owner_id`. Returns `true` iff a live row
/// was stamped. Stamping is idempotent — a second DELETE on the same slug
/// just returns `false` because the row is already marked.
pub async fn delete(pool: &PgPool, slug: &str, owner_id: Uuid) -> Result<bool, sqlx::Error> {
    let res = sqlx::query!(
        "UPDATE snippets SET deleted_at = now()
            WHERE slug = $1 AND owner_id = $2 AND deleted_at IS NULL",
        slug,
        owner_id,
    )
    .execute(pool)
    .await?;
    Ok(res.rows_affected() > 0)
}

/// Patch the sharing-policy fields on a live snippet. `None` on a field
/// means "leave it alone"; `Some(_)` writes the new value. The handler is
/// responsible for converting the user's `lifetime_seconds` choice into an
/// absolute `expires_at` (the inner `Option<DateTime>` allows `Some(None)`
/// to clear expiry entirely).
///
/// Disabling burn-after-read also clears `first_viewed_at` so the 15-min
/// timer is fully cancelled (a later re-enable shouldn't fire an
/// already-spent fuse).
#[derive(Debug, Default)]
pub struct SettingsPatch {
    pub visibility: Option<Visibility>,
    pub expires_at: Option<Option<OffsetDateTime>>,
    pub burn_after_read: Option<bool>,
}

pub async fn update_settings(
    pool: &PgPool,
    slug: &str,
    owner_id: Uuid,
    patch: SettingsPatch,
) -> Result<Option<SnippetRow>, sqlx::Error> {
    let visibility_str = patch.visibility.map(|v| v.as_str().to_string());
    let set_visibility = visibility_str.is_some();

    let (set_expires, expires_value) = match patch.expires_at {
        Some(opt) => (true, opt),
        None => (false, None),
    };

    let (set_burn, burn_value) = match patch.burn_after_read {
        Some(b) => (true, b),
        None => (false, false),
    };

    let res = sqlx::query!(
        "UPDATE snippets
            SET visibility = CASE WHEN $3 THEN $4 ELSE visibility END,
                expires_at = CASE WHEN $5 THEN $6 ELSE expires_at END,
                burn_after_read = CASE WHEN $7 THEN $8 ELSE burn_after_read END,
                first_viewed_at = CASE
                    WHEN $7 AND $8 = false THEN NULL
                    ELSE first_viewed_at
                END
            WHERE slug = $1 AND owner_id = $2 AND deleted_at IS NULL",
        slug,
        owner_id,
        set_visibility,
        visibility_str,
        set_expires,
        expires_value,
        set_burn,
        burn_value,
    )
    .execute(pool)
    .await?;
    if res.rows_affected() == 0 {
        return Ok(None);
    }
    by_slug(pool, slug).await
}

#[derive(Debug, Default)]
pub struct SnippetPatch<'a> {
    pub body: Option<&'a str>,
    pub name: Option<Option<&'a str>>, // double Option: outer = "did caller supply", inner = the value (NULL allowed)
}

/// Update body, name, or both. Split into 4 static queries (3 distinct UPDATEs
/// plus an early-return for the "no fields" case) so each SQL string is fully
/// known at compile time and can be macro-checked.
pub async fn update(
    pool: &PgPool,
    slug: &str,
    owner_id: Uuid,
    patch: SnippetPatch<'_>,
) -> Result<Option<SnippetRow>, sqlx::Error> {
    let body = patch.body;
    let size = body.map(|b| i32::try_from(b.len()).unwrap_or(i32::MAX));
    let (set_name, name_value) = match patch.name {
        Some(v) => (true, v),
        None => (false, None),
    };

    let rows_affected = match (body, set_name) {
        (Some(b), true) => sqlx::query!(
            "UPDATE snippets SET body = $3, size_bytes = $4, name = $5
             WHERE slug = $1 AND owner_id = $2 AND deleted_at IS NULL",
            slug,
            owner_id,
            b,
            size.unwrap(),
            name_value,
        )
        .execute(pool)
        .await?
        .rows_affected(),
        (Some(b), false) => sqlx::query!(
            "UPDATE snippets SET body = $3, size_bytes = $4
             WHERE slug = $1 AND owner_id = $2 AND deleted_at IS NULL",
            slug,
            owner_id,
            b,
            size.unwrap(),
        )
        .execute(pool)
        .await?
        .rows_affected(),
        (None, true) => sqlx::query!(
            "UPDATE snippets SET name = $3
             WHERE slug = $1 AND owner_id = $2 AND deleted_at IS NULL",
            slug,
            owner_id,
            name_value,
        )
        .execute(pool)
        .await?
        .rows_affected(),
        (None, false) => {
            return by_slug(pool, slug)
                .await
                .map(|opt| opt.filter(|r| r.owner_id == owner_id));
        }
    };
    if rows_affected == 0 {
        return Ok(None);
    }
    by_slug(pool, slug).await
}

/// Record a unique-viewer hit. Inserts into `snippet_views` and bumps
/// `snippets.views` only when the row was actually new.
pub async fn record_view(
    pool: &PgPool,
    snippet_id: Uuid,
    viewer_hash: &[u8; 32],
) -> Result<bool, sqlx::Error> {
    let hash_slice: &[u8] = viewer_hash;
    let inserted = sqlx::query!(
        "INSERT INTO snippet_views (snippet_id, viewer_hash)
         VALUES ($1, $2)
         ON CONFLICT DO NOTHING",
        snippet_id,
        hash_slice,
    )
    .execute(pool)
    .await?;
    if inserted.rows_affected() == 0 {
        return Ok(false);
    }
    sqlx::query!(
        "UPDATE snippets SET views = views + 1 WHERE id = $1",
        snippet_id,
    )
    .execute(pool)
    .await?;
    Ok(true)
}

pub struct ListFilter<'a> {
    pub owner_id: Uuid,
    pub kind: Option<SnippetType>,
    pub cursor: Option<&'a OffsetDateTime>,
    pub limit: i64,
}

pub async fn list_for_user(
    pool: &PgPool,
    filter: ListFilter<'_>,
) -> Result<Vec<SnippetRow>, sqlx::Error> {
    let rows = match (filter.kind, filter.cursor) {
        (Some(k), Some(c)) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.views,
                      s.visibility, s.expires_at, s.burn_after_read,
                      s.first_viewed_at, s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1 AND s.type = $2 AND s.created_at < $3
                 AND s.deleted_at IS NULL
               ORDER BY s.created_at DESC
               LIMIT $4"#,
            filter.owner_id,
            k.as_str(),
            c,
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
        (Some(k), None) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.views,
                      s.visibility, s.expires_at, s.burn_after_read,
                      s.first_viewed_at, s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1 AND s.type = $2
                 AND s.deleted_at IS NULL
               ORDER BY s.created_at DESC
               LIMIT $3"#,
            filter.owner_id,
            k.as_str(),
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
        (None, Some(c)) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.views,
                      s.visibility, s.expires_at, s.burn_after_read,
                      s.first_viewed_at, s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1 AND s.created_at < $2
                 AND s.deleted_at IS NULL
               ORDER BY s.created_at DESC
               LIMIT $3"#,
            filter.owner_id,
            c,
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
        (None, None) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.views,
                      s.visibility, s.expires_at, s.burn_after_read,
                      s.first_viewed_at, s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1
                 AND s.deleted_at IS NULL
               ORDER BY s.created_at DESC
               LIMIT $2"#,
            filter.owner_id,
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
    };
    Ok(rows.into_iter().filter_map(map).collect())
}
