use paste_core::SnippetType;
use sqlx::PgPool;
use time::OffsetDateTime;
use uuid::Uuid;

#[derive(Debug, Clone)]
pub struct SnippetRow {
    pub id: Uuid,
    pub slug: String,
    pub owner_id: Uuid,
    pub owner_username: String,
    pub kind: SnippetType,
    pub name: Option<String>,
    pub body: String,
    pub size_bytes: i32,
    pub visibility: String,
    pub views: i32,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

#[derive(Debug)]
pub struct SnippetDraft<'a> {
    pub owner_id: Uuid,
    pub kind: SnippetType,
    pub name: Option<&'a str>,
    pub body: &'a str,
}

/// Raw-row destination. `kind` is stored as CHECK-constrained `varchar` so
/// sqlx sees it as `String`; mapped to `SnippetType` after fetch.
struct SnippetRowRaw {
    id: Uuid,
    slug: String,
    owner_id: Uuid,
    owner_username: String,
    kind: String,
    name: Option<String>,
    body: String,
    size_bytes: i32,
    visibility: String,
    views: i32,
    created_at: OffsetDateTime,
    updated_at: OffsetDateTime,
}

fn map(r: SnippetRowRaw) -> Option<SnippetRow> {
    Some(SnippetRow {
        id: r.id,
        slug: r.slug,
        owner_id: r.owner_id,
        owner_username: r.owner_username,
        kind: r.kind.parse().ok()?,
        name: r.name,
        body: r.body,
        size_bytes: r.size_bytes,
        visibility: r.visibility,
        views: r.views,
        created_at: r.created_at,
        updated_at: r.updated_at,
    })
}

/// Insert a snippet at the given `slug`. The slug is generated by the caller
/// (see [`super::slug::create_with_retry`]) so we can react to collisions.
pub async fn insert<'a>(
    pool: &PgPool,
    slug: &str,
    draft: &SnippetDraft<'a>,
) -> Result<SnippetRow, sqlx::Error> {
    let size = i32::try_from(draft.body.len()).unwrap_or(i32::MAX);
    let inserted_id = sqlx::query!(
        "INSERT INTO snippets (slug, owner_id, type, name, body, size_bytes)
         VALUES ($1, $2, $3, $4, $5, $6)
         RETURNING id",
        slug,
        draft.owner_id,
        draft.kind.as_str(),
        draft.name,
        draft.body,
        size,
    )
    .fetch_one(pool)
    .await?;
    by_id(pool, inserted_id.id)
        .await?
        .ok_or(sqlx::Error::RowNotFound)
}

/// Fetch a snippet by primary key, joined to its owner's username.
pub async fn by_id(pool: &PgPool, id: Uuid) -> Result<Option<SnippetRow>, sqlx::Error> {
    let row = sqlx::query_as!(
        SnippetRowRaw,
        r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                  s.type AS kind, s.name, s.body, s.size_bytes, s.visibility, s.views,
                  s.created_at, s.updated_at
           FROM snippets s
           JOIN users u ON u.id = s.owner_id
           WHERE s.id = $1"#,
        id,
    )
    .fetch_optional(pool)
    .await?;
    Ok(row.and_then(map))
}

/// Fetch a snippet by its public slug, joined to its owner's username.
pub async fn by_slug(pool: &PgPool, slug: &str) -> Result<Option<SnippetRow>, sqlx::Error> {
    let row = sqlx::query_as!(
        SnippetRowRaw,
        r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                  s.type AS kind, s.name, s.body, s.size_bytes, s.visibility, s.views,
                  s.created_at, s.updated_at
           FROM snippets s
           JOIN users u ON u.id = s.owner_id
           WHERE s.slug = $1"#,
        slug,
    )
    .fetch_optional(pool)
    .await?;
    Ok(row.and_then(map))
}

/// Delete a snippet owned by `owner_id`. Returns `true` iff a row was removed.
pub async fn delete(pool: &PgPool, slug: &str, owner_id: Uuid) -> Result<bool, sqlx::Error> {
    let res = sqlx::query!(
        "DELETE FROM snippets WHERE slug = $1 AND owner_id = $2",
        slug,
        owner_id,
    )
    .execute(pool)
    .await?;
    Ok(res.rows_affected() > 0)
}

#[derive(Debug, Default)]
pub struct SnippetPatch<'a> {
    pub body: Option<&'a str>,
    pub name: Option<Option<&'a str>>, // double Option: outer = "did caller supply", inner = the value (NULL allowed)
}

/// Update body, name, or both. Split into 4 static queries (3 distinct UPDATEs
/// plus an early-return for the "no fields" case) so each SQL string is fully
/// known at compile time and can be macro-checked.
pub async fn update(
    pool: &PgPool,
    slug: &str,
    owner_id: Uuid,
    patch: SnippetPatch<'_>,
) -> Result<Option<SnippetRow>, sqlx::Error> {
    let body = patch.body;
    let size = body.map(|b| i32::try_from(b.len()).unwrap_or(i32::MAX));
    let (set_name, name_value) = match patch.name {
        Some(v) => (true, v),
        None => (false, None),
    };

    let rows_affected = match (body, set_name) {
        (Some(b), true) => sqlx::query!(
            "UPDATE snippets SET body = $3, size_bytes = $4, name = $5
             WHERE slug = $1 AND owner_id = $2",
            slug,
            owner_id,
            b,
            size.unwrap(),
            name_value,
        )
        .execute(pool)
        .await?
        .rows_affected(),
        (Some(b), false) => sqlx::query!(
            "UPDATE snippets SET body = $3, size_bytes = $4
             WHERE slug = $1 AND owner_id = $2",
            slug,
            owner_id,
            b,
            size.unwrap(),
        )
        .execute(pool)
        .await?
        .rows_affected(),
        (None, true) => sqlx::query!(
            "UPDATE snippets SET name = $3
             WHERE slug = $1 AND owner_id = $2",
            slug,
            owner_id,
            name_value,
        )
        .execute(pool)
        .await?
        .rows_affected(),
        (None, false) => {
            // Nothing to change; just return the current row if it belongs to the caller.
            return by_slug(pool, slug)
                .await
                .map(|opt| opt.filter(|r| r.owner_id == owner_id));
        }
    };
    if rows_affected == 0 {
        return Ok(None);
    }
    by_slug(pool, slug).await
}

/// Bump the `views` counter by one. Best-effort; the GET handler kicks this
/// off in a detached task.
pub async fn incr_views(pool: &PgPool, slug: &str) -> Result<(), sqlx::Error> {
    sqlx::query!(
        "UPDATE snippets SET views = views + 1 WHERE slug = $1",
        slug,
    )
    .execute(pool)
    .await?;
    Ok(())
}

pub struct ListFilter<'a> {
    pub owner_id: Uuid,
    pub kind: Option<SnippetType>,
    pub cursor: Option<&'a OffsetDateTime>,
    pub limit: i64,
}

/// List snippets owned by a user, with optional type/cursor filters. Split
/// into the 4 (kind Some/None) × (cursor Some/None) combinations so each
/// query string is statically checkable.
pub async fn list_for_user(
    pool: &PgPool,
    filter: ListFilter<'_>,
) -> Result<Vec<SnippetRow>, sqlx::Error> {
    let rows = match (filter.kind, filter.cursor) {
        (Some(k), Some(c)) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.visibility, s.views,
                      s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1 AND s.type = $2 AND s.created_at < $3
               ORDER BY s.created_at DESC
               LIMIT $4"#,
            filter.owner_id,
            k.as_str(),
            c,
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
        (Some(k), None) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.visibility, s.views,
                      s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1 AND s.type = $2
               ORDER BY s.created_at DESC
               LIMIT $3"#,
            filter.owner_id,
            k.as_str(),
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
        (None, Some(c)) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.visibility, s.views,
                      s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1 AND s.created_at < $2
               ORDER BY s.created_at DESC
               LIMIT $3"#,
            filter.owner_id,
            c,
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
        (None, None) => sqlx::query_as!(
            SnippetRowRaw,
            r#"SELECT s.id, s.slug, s.owner_id, u.username AS owner_username,
                      s.type AS kind, s.name, s.body, s.size_bytes, s.visibility, s.views,
                      s.created_at, s.updated_at
               FROM snippets s
               JOIN users u ON u.id = s.owner_id
               WHERE s.owner_id = $1
               ORDER BY s.created_at DESC
               LIMIT $2"#,
            filter.owner_id,
            filter.limit,
        )
        .fetch_all(pool)
        .await?,
    };
    Ok(rows.into_iter().filter_map(map).collect())
}
