export function mapHljsLanguageToShiki(hljsLang: string): string {
  const languageMap: Record<string, string> = {
    // Programming languages - only mapping to Shiki-supported languages
    "actionscript": "javascript",
    "arduino": "cpp",
    "aspectj": "java",
    "bash": "shellscript",
    "c": "c",
    "c++": "cpp",
    "cpp": "cpp",
    "coffeescript": "coffeescript",
    "coffee": "coffeescript",
    "css": "css",
    "glsl": "glsl",
    "graphql": "graphql",
    "gql": "graphql",
    "haml": "haml",
    "handlebars": "handlebars",
    "hbs": "handlebars",
    "html": "html",
    "http": "http",
    "java": "java",
    "javascript": "javascript",
    "js": "javascript",
    "json": "json",
    "json5": "json5",
    "jsonc": "jsonc",
    "jsonl": "jsonl",
    "julia": "julia",
    "jl": "julia",
    "julia-repl": "julia",
    "jsx": "jsx",
    "less": "less",
    "markdown": "markdown",
    "md": "markdown",
    "node-repl": "javascript",
    "pgsql": "sql",
    "php": "php",
    "php-template": "php",
    "postcss": "postcss",
    "pug": "pug",
    "jade": "pug",
    "python": "python",
    "py": "python",
    "python-repl": "python",
    "r": "r",
    "regexp": "regexp",
    "regex": "regexp",
    "sass": "sass",
    "scss": "scss",
    "sh": "shellscript",
    "shell": "shellscript",
    "shellscript": "shellscript",
    "zsh": "shellscript",
    "sql": "sql",
    "stylus": "stylus",
    "styl": "stylus",
    "svelte": "svelte",
    "ts": "typescript",
    "typescript": "typescript",
    "tsx": "tsx",
    "vbscript-html": "html",
    "vue": "vue",
    "wasm": "wasm",
    "wgsl": "wgsl",
    "wit": "wit",
    "xml": "xml",
    "yaml": "yaml",
    "yml": "yaml",
    
    // Web framework specific - Shiki supported
    "angular-html": "angular-html",
    "angular-ts": "angular-ts",
    "astro": "astro",
    "blade": "blade",
    "imba": "imba",
    "jinja": "jinja",
    "jison": "jison",
    "marko": "marko",
    "mdc": "mdc",
    "mdx": "mdx",
    "ts-tags": "ts-tags",
    "lit": "ts-tags",
    "vue-html": "vue-html",
    "vue-vine": "vue-vine",
    
    // Common aliases - fallback to text for unsupported languages
    "plaintext": "text"
  };

  return languageMap[hljsLang.toLowerCase()] || "text";
}